# -*- coding: utf-8 -*-
"""图表工作室页面 — Python 优先架构

可视化的 Python 数据分析平台，支持 Plotly 和 Seaborn 两种图表库。
所有操作可导出为可执行的 Python 代码。
"""

from __future__ import annotations

import dash_bootstrap_components as dbc
from dash import html, dcc, callback, Input, Output, State, no_update, ctx, MATCH, ALL
import pandas as pd
import json
import io
import uuid
from datetime import datetime
import requests
import plotly.graph_objects as go

from core.data_manager import DataManager
from components.code_preview import create_code_preview_panel
from services.chart_service import ChartService, ChartLibrary, ChartType, PLOTLY_CHART_TYPES, SEABORN_CHART_TYPES
from services.code_generator import CodeGenerator
from services.field_analyzer import get_labeled_options
from services.chart_recommender import ChartRecommender


def _build_chart_config(library: str, chart_type: str, params: dict, title: str | None = None) -> dict:
    return {
        'library': library,
        'chart_type': chart_type,
        'params': params,
        'title': title or params.get('title') or params.get('chart_title'),
    }


def _normalize_saved_chart(item: dict | None) -> dict | None:
    if not isinstance(item, dict):
        return None
    library = item.get('library') or item.get('config', {}).get('library')
    chart_type = item.get('chart_type') or item.get('config', {}).get('chart_type') or 'chart'
    config = item.get('config') if isinstance(item.get('config'), dict) else {}
    figure = item.get('figure')
    if isinstance(figure, dict):
        if 'plotly' in figure:
            library = library or 'plotly'
            figure = json.dumps(figure['plotly'], ensure_ascii=False)
        elif 'seaborn' in figure:
            library = library or 'seaborn'
            figure = figure['seaborn']
    if not library:
        if isinstance(figure, str):
            library = 'seaborn' if figure.startswith('data:image') else 'plotly'
        else:
            library = 'plotly'
    merged_config = {
        'library': library,
        'chart_type': chart_type,
        'params': config.get('params', item.get('params', {})) or {},
        'title': config.get('title') or item.get('title'),
    }
    return {
        'id': item.get('id') or f"chart_{uuid.uuid4().hex}",
        'timestamp': item.get('timestamp') or '',
        'library': library,
        'chart_type': chart_type,
        'figure': figure,
        'config': merged_config,
    }


def _build_notebook_content(code: str, chart_config: dict | None) -> str:
    title = chart_config.get('title') if chart_config else None
    title = title or (chart_config.get('chart_type') if chart_config else None) or 'Chart Studio Export'
    markdown_lines = [f'# {title}', '', 'Generated by DataViz Studio.']
    if chart_config:
        markdown_lines.extend(['', f"- library: {chart_config.get('library', 'unknown')}", f"- chart_type: {chart_config.get('chart_type', 'unknown')}"])
    notebook = {
        'cells': [
            {'cell_type': 'markdown', 'metadata': {}, 'source': [line + '\n' for line in markdown_lines]},
            {'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [], 'source': [line + '\n' for line in code.splitlines()]},
        ],
        'metadata': {
            'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
            'language_info': {'name': 'python', 'version': '3'},
        },
        'nbformat': 4,
        'nbformat_minor': 5,
    }
    return json.dumps(notebook, ensure_ascii=False, indent=2)


def _render_chart_from_state(fig_data, chart_config):
    if not fig_data or not chart_config:
        return no_update
    library = chart_config.get("library")
    if library == "plotly":
        try:
            figure = json.loads(fig_data) if isinstance(fig_data, str) else fig_data
        except Exception:
            return html.Div("图表恢复失败", className="text-danger")
        return dcc.Graph(
            figure=figure,
            config={"displayModeBar": True, "displaylogo": False},
            style={"height": "100%"},
        )
    if library == "seaborn":
        return html.Img(
            src=fig_data,
            style={"width": "100%", "maxHeight": "500px", "objectFit": "contain"},
        )
    return no_update


def _build_editor_prefill(item: dict | None) -> dict | None:
    normalized = _normalize_saved_chart(item)
    if not normalized:
        return None

    config = normalized.get("config") or {}
    params = dict(config.get("params") or {})
    params.setdefault("title", config.get("title"))
    params.setdefault("template", "plotly_white")
    params.setdefault("color_scale", "")
    params.setdefault("show_legend", True)
    params.setdefault("show_grid", True)
    params.setdefault("opacity", 1.0)

    return {
        "pending": True,
        "library": normalized.get("library") or config.get("library") or "plotly",
        "chart_type": normalized.get("chart_type"),
        "params": params,
        "figure": normalized.get("figure"),
        "config": config,
    }



def create_chart_studio_page() -> html.Div:
    """创建图表工作室页面"""
    dm = DataManager()
    df = dm.active_df

    if df is None or df.empty:
        return html.Div([
            dbc.Alert(
                [
                    html.I(className="bi bi-exclamation-triangle me-2"),
                    "请先在数据中心加载数据"
                ],
                color="warning",
                className="m-4"
            )
        ])

    return html.Div([
        # 顶部：图表库切换器
        html.Div([
            html.Label("图表引擎：", className="me-3 fw-bold"),
            dbc.RadioItems(
                id='chart-library-selector',
                options=[
                    {'label': '📊 Plotly (交互式)', 'value': 'plotly'},
                    {'label': '🎨 Seaborn (静态制图)', 'value': 'seaborn'}
                ],
                value='plotly',
                className='btn-group',
                inputClassName='btn-check',
                labelClassName='btn btn-outline-primary',
                labelCheckedClassName='active btn-primary',
                labelCheckedStyle={"backgroundColor": "var(--primary)", "color": "white", "borderColor": "var(--primary)", "fontWeight": "600"},
            ),
            html.Div(id='library-info', className='library-info text-muted ms-3')
        ], className='library-switcher p-3 border-bottom fade-in d-flex align-items-center'),

        # 主模块 Tabs
        dbc.Tabs([
            dbc.Tab(label="✨ 图表探索", tab_id="tab-explore", children=[
                # 原主内容区
                dbc.Row([
            # 左侧：参数配置面板
            dbc.Col([
                html.Div([
                    # 智能推荐区域
                    html.Div(
                        id='chart-recommend-area',
                        children=[
                            html.Div([
                                html.Span("📌", className="me-1"),
                                html.Span("智能推荐", style={"fontWeight": "600", "fontSize": "0.85rem"}),
                            ], className="mb-2", style={"color": "var(--accent)"}),
                            html.Div(
                                "选择 X/Y 轴后将显示推荐图表",
                                id='chart-recommendations',
                                style={"fontSize": "0.8rem", "color": "var(--text-muted)"},
                            ),
                        ],
                        className='mb-3 p-2 dvs-alert dvs-alert--info'
                    ),

                    html.H6("图表类型", className="mb-3"),
                    dcc.Dropdown(
                        id='chart-type-selector',
                        options=[],
                        value='scatter',
                        placeholder='选择图表类型',
                        className='mb-3'
                    ),

                    html.Hr(),

                    # 参数配置区域（初始加载Plotly参数面板）
                    html.Div(
                        id='params-panel-container',
                        children=create_plotly_params_panel(df) if df is not None else html.Div()
                    ),

                ], className='p-3 slide-in-left')
            ], width=3, className='border-end', style={'height': 'calc(100vh - 140px)', 'overflowY': 'auto'}),

            # 中间：图表画布
            dbc.Col([
                html.Div([
                    html.Div(id='chart-container', children=[
                        html.Div([
                            html.I(className="bi bi-graph-up", style={'fontSize': '48px', 'color': '#6366F1'}),
                            html.P("👈 配置参数后，图表将在这里显示",
                                   className='placeholder-text mt-3')
                        ], className='chart-placeholder text-center',
                           style={'paddingTop': '100px'})
                    ], className='fade-in', style={'height': '60%', 'borderBottom': '1px solid var(--border)'}),

                    # 导出按钮行
                    html.Div([
                        dbc.Button([
                            html.I(className="bi bi-file-image me-1"), "导出PNG"
                        ], id='export-png-btn', color='outline-primary', size='sm', className='me-2 btn-hover'),
                        dbc.Button([
                            html.I(className="bi bi-filetype-svg me-1"), "导出SVG"
                        ], id='export-svg-btn', color='outline-info', size='sm', className='me-2 btn-hover'),
                        dbc.Button([
                            html.I(className="bi bi-filetype-html me-1"), "导出HTML"
                        ], id='export-html-btn', color='outline-success', size='sm', className='btn-hover'),
                        
                        html.Div(style={"flex": "1"}),
                        
                        dbc.Button([
                            html.I(className="bi bi-bookmark-heart me-1"), "保存至画廊"
                        ], id='btn-save-chart', color='warning', size='sm', className='btn-hover shadow-sm', style={"color": "#fff"}),
                    ], className='d-flex align-items-center p-2 border-bottom'),

                    # 代码预览面板
                    create_code_preview_panel(),

                ], className='p-3')
            ], width=9, style={'height': 'calc(100vh - 140px)', 'overflowY': 'auto'}),

        ], className='g-0')
            ]), # 结束 Tab 1

            dbc.Tab(label="🖼️ 图表画廊", tab_id="tab-gallery", children=[
                html.Div([
                    html.Div([
                        html.H5("已保存的图表模型", className="mb-0"),
                        dbc.Button([
                            html.I(className="bi bi-trash me-2"), "清空画廊"
                        ], id="btn-clear-gallery", color="danger", outline=True, size="sm")
                    ], className="d-flex justify-content-between align-items-center mb-4"),
                    html.Div(id="chart-gallery-grid")
                ], className="p-4", style={'height': 'calc(100vh - 140px)', 'overflowY': 'auto'})
            ]), # 结束 Tab 2

            dbc.Tab(label="🧠 图表分析", tab_id="tab-analysis", children=[
                dbc.Row([
                    # 左侧：当前图表快照
                    dbc.Col([
                        html.H6([html.I(className="bi bi-image me-2"), "当前图表快照"], className="mb-3", style={"color": "var(--text-muted)"}),
                        dbc.Card(
                            dbc.CardBody([
                                html.Div(id="ai-chart-display", className="d-flex align-items-center justify-content-center w-100 h-100 text-muted", children="分析区会同步你最后生成的图表...")
                            ]),
                            style={"height": "100%", "backgroundColor": "var(--bg-secondary)", "border": "1px dashed var(--border)"}
                        )
                    ], width=5, className="p-4 border-end", style={"height": "calc(100vh - 140px)"}),

                    # 右侧：AI 配置与输出
                    dbc.Col([
                        # API 配置折叠面板
                        dbc.Accordion([
                            dbc.AccordionItem([
                                dbc.Row([
                                    dbc.Col([
                                        html.Label("API 协议地址 (Base URL)", className="form-label small"),
                                        dbc.Input(id="ai-api-base", value="https://api.openai.com/v1", size="sm")
                                    ], width=6),
                                    dbc.Col([
                                        html.Label("模型名称 (Model)", className="form-label small"),
                                        dbc.Input(id="ai-api-model", value="gpt-3.5-turbo", size="sm")
                                    ], width=6)
                                ], className="mb-2"),
                                dbc.Row([
                                    dbc.Col([
                                        html.Label("API 密钥 (API Key)", className="form-label small"),
                                        dbc.Input(id="ai-api-key", type="password", placeholder="sk-...", size="sm")
                                    ], width=12)
                                ])
                            ], title="⚙️ AI 引擎配置 (支持兼容 OpenAI 接口的大模型)", item_id="api-config")
                        ], start_collapsed=True, className="mb-4 shadow-sm"),

                        # 操作与提示
                        html.Div([
                            dbc.Button([html.I(className="bi bi-magic me-2"), "生成深度分析结论"], id="btn-generate-ai", color="primary", className="flex-grow-1 shadow-sm rounded-pill"),
                        ], className="d-flex w-100 mb-4"),

                        # 输出区域
                        html.H6("💡 AI 洞察结果", className="mb-2", style={"fontWeight": "600"}),
                        dbc.Card(
                            dbc.CardBody([
                                dcc.Loading(
                                    type="dot", color="#FF6B35",
                                    children=dcc.Markdown(id="ai-analysis-output", className="markdown-body p-2", children="* 填写配置并点击「生成深度分析结论」开始解读... *")
                                )
                            ]),
                            style={"height": "calc(100% - 240px)", "overflowY": "auto", "backgroundColor": "#F8FAFC"}
                        )
                    ], width=7, className="p-4", style={"height": "calc(100vh - 140px)"})
                ], className="g-0")
            ]), # 结束 Tab 3
        ], id="chart-studio-tabs", active_tab="tab-explore", className="mt-2 px-3"),

        # 存储组件
        dcc.Store(id='chart-data-store'),
        dcc.Store(id='chart-figure-store'),
        dcc.Store(id='saved-charts-store', storage_type='local', data=[]),  # 画廊本地存储
        dcc.Store(id='chart-editor-prefill-store', data=None),
        dcc.Download(id='download-chart-file'),
        dcc.Download(id='download-jupyter-file'),

        # Toast 提示
        html.Div([
            dbc.Toast(
                "代码已复制到剪贴板",
                id="copy-success-toast",
                header="成功",
                is_open=False,
                dismissable=True,
                icon="success",
                duration=2000,
            ),
            dbc.Toast(
                "图表已成功保存至画廊！",
                id="save-success-toast",
                header="保存成功",
                is_open=False,
                dismissable=True,
                icon="success",
                duration=3000,
            )
        ], style={"position": "fixed", "top": 66, "right": 10, "width": 350, "zIndex": 9999, "display": "flex", "flexDirection": "column", "gap": "10px"}),

    ], id='chart-studio-page')


def _create_style_panel(defaults: dict | None = None) -> html.Div:
    """创建图表样式配置区域"""
    defaults = defaults or {}
    return html.Div([
        html.Hr(),
        html.H6("图表样式", className="mb-3 mt-2"),

        # 标题
        html.Div([
            html.Label("图表标题", className="form-label"),
            dbc.Input(
                id='style-title',
                type='text',
                placeholder='输入图表标题（可选）',
                value=defaults.get('title'),
                size='sm',
                className='mb-2'
            ),
        ]),

        # 主题
        html.Div([
            html.Label("主题模板", className="form-label"),
            dcc.Dropdown(
                id='style-template',
                options=[
                    {'label': '明亮主题', 'value': 'plotly_white'},
                    {'label': '极简无边界', 'value': 'simple_white'},
                    {'label': '暗黑主题', 'value': 'plotly_dark'}
                ],
                value=defaults.get('template', 'plotly_white'),
                clearable=False,
                className='mb-2'
            ),
        ]),

        # 配色
        html.Div([
            html.Label("配色方案", className="form-label"),
            dcc.Dropdown(
                id='style-color-scale',
                options=[
                    {'label': '默认', 'value': ''},
                    {'label': 'Viridis', 'value': 'Viridis'},
                    {'label': 'Plasma', 'value': 'Plasma'},
                    {'label': 'Inferno', 'value': 'Inferno'},
                    {'label': 'Magma', 'value': 'Magma'},
                    {'label': 'Cividis', 'value': 'Cividis'},
                    {'label': 'Turbo', 'value': 'Turbo'},
                    {'label': 'Bluered', 'value': 'Bluered'},
                    {'label': 'Rainbow', 'value': 'Rainbow'},
                ],
                value=defaults.get('color_scale', ''),
                clearable=True,
                className='mb-2'
            ),
        ]),

        # 显示图例
        html.Div([
            dbc.Checkbox(
                id='style-show-legend',
                label='显示图例',
                value=defaults.get('show_legend', True),
                className='mb-2'
            ),
        ]),

        # 显示网格
        html.Div([
            dbc.Checkbox(
                id='style-show-grid',
                label='显示网格',
                value=defaults.get('show_grid', True),
                className='mb-2'
            ),
        ]),

        # 启动辅助 Y 轴 (已被移至特征参数面板)

        # 透明度
        html.Div([
            html.Label("不透明度 (Opacity)", className="form-label"),
            dbc.Input(
                id='style-opacity',
                type='number',
                min=0.1, max=1.0, step=0.1,
                value=defaults.get('opacity', 1.0),
                size='sm',
                className='mb-2'
            ),
        ]),

        # 尺寸
        dbc.Row([
            dbc.Col([
                html.Label("宽度", className="form-label"),
                dbc.Input(
                    id='style-width',
                    type='number',
                    placeholder='自动',
                    value=defaults.get('width'),
                    size='sm',
                    className='mb-2'
                ),
            ], width=6),
            dbc.Col([
                html.Label("高度", className="form-label"),
                dbc.Input(
                    id='style-height',
                    type='number',
                    placeholder='自动',
                    value=defaults.get('height'),
                    size='sm',
                    className='mb-2'
                ),
            ], width=6),
        ]),
    ])


def create_plotly_params_panel(df: pd.DataFrame, defaults: dict | None = None) -> html.Div:
    """创建 Plotly 参数配置面板"""
    defaults = defaults or {}
    columns = get_labeled_options(df)

    return html.Div([
        html.H6("Plotly Express 参数", className="mb-3"),

        # 基础参数
        html.Div([
            html.Label("x (X轴)", className="form-label"),
            dcc.Dropdown(
                id='param-x',
                options=columns,
                value=defaults.get('x'),
                placeholder='选择X轴字段',
                className='mb-2'
            ),
        ], id='wrapper-param-x'),

        html.Div([
            html.Label("y (Y轴)", className="form-label"),
            dcc.Dropdown(
                id='param-y',
                options=columns,
                value=defaults.get('y'),
                placeholder='选择Y轴字段',
                className='mb-2'
            ),
            dbc.Checkbox(
                id='param-secondary-y-check',
                label='启用双 Y 轴',
                value=bool(defaults.get('secondary_y')),
                className='mb-1 mt-2',
                style={'fontSize': '12px', 'color': 'var(--text-muted)'}
            ),
            html.Div(id='wrap-secondary-y-col', style={'display': 'none'}, children=[
                dcc.Dropdown(
                    id='param-secondary-y-col',
                    options=columns,
                    value=defaults.get('secondary_y'),
                    placeholder='选择额外 Y 轴列',
                    className='mb-2',
                    clearable=True
                )
            ])
        ], id='wrapper-param-y'),

        html.Div([
            html.Label("z (Z轴/限3D场景)", className="form-label"),
            dcc.Dropdown(
                id='param-z',
                options=columns,
                value=defaults.get('z'),
                placeholder='选择Z轴字段',
                clearable=True,
                className='mb-2'
            ),
        ], id='wrapper-param-z', style={'display': 'none'}),

        html.Div([
            html.Label("color (颜色分组)", className="form-label"),
            dcc.Dropdown(
                id='param-color',
                options=columns,
                value=defaults.get('color'),
                placeholder='选择颜色字段（可选）',
                clearable=True,
                className='mb-2'
            ),
        ], id='wrapper-param-color'),

        html.Div([
            html.Label("size (大小)", className="form-label"),
            dcc.Dropdown(
                id='param-size',
                options=columns,
                value=defaults.get('size'),
                placeholder='选择大小字段（可选）',
                clearable=True,
                className='mb-2'
            ),
        ], id='wrapper-param-size'),

        html.Div([
            html.Label("text (数据标签)", className="form-label"),
            dcc.Dropdown(
                id='param-text',
                options=columns,
                value=defaults.get('text'),
                placeholder='选择图形上的悬停/常显文本',
                clearable=True,
                className='mb-2'
            ),
        ], id='wrapper-param-text'),

        # 高级参数（可折叠）
        html.Hr(),
        dbc.Button(
            "展开高级参数",
            id='toggle-advanced-params',
            size='sm',
            color='link',
            className='mb-2 btn-hover'
        ),

        dbc.Collapse([
            html.H6("高级参数", className="mb-2 mt-2"),

            html.Div([
                html.Label("hover_data (悬停显示)", className="form-label"),
                dcc.Dropdown(
                    id='param-hover-data',
                    options=columns,
                    value=defaults.get('hover_data'),
                    placeholder='选择悬停字段（可多选）',
                    multi=True,
                    className='mb-2'
                ),
            ], id='wrapper-param-hover-data'),

            html.Div([
                html.Label("facet_row (分面行)", className="form-label"),
                dcc.Dropdown(
                    id='param-facet-row',
                    options=columns,
                    value=defaults.get('facet_row'),
                    placeholder='选择分面行字段（可选）',
                    clearable=True,
                    className='mb-2'
                ),
            ], id='wrapper-param-facet-row'),

            html.Div([
                html.Label("facet_col (分面列)", className="form-label"),
                dcc.Dropdown(
                    id='param-facet-col',
                    options=columns,
                    value=defaults.get('facet_col'),
                    placeholder='选择分面列字段（可选）',
                    clearable=True,
                    className='mb-2'
                ),
            ], id='wrapper-param-facet-col'),

            html.Div([
                html.Label("animation_frame (动画帧)", className="form-label"),
                dcc.Dropdown(
                    id='param-animation-frame',
                    options=columns,
                    value=defaults.get('animation_frame'),
                    placeholder='选择动画帧字段（可选）',
                    clearable=True,
                    className='mb-2'
                ),
            ], id='wrapper-param-animation-frame'),

            html.Div([
                html.Label("trendline (趋势线)", className="form-label"),
                dcc.Dropdown(
                    id='param-trendline',
                    options=[
                        {'label': 'OLS回归', 'value': 'ols'},
                        {'label': 'LOWESS平滑', 'value': 'lowess'},
                    ],
                    value=defaults.get('trendline'),
                    placeholder='选择趋势线类型（可选）',
                    clearable=True,
                    className='mb-2'
                ),
            ], id='wrapper-param-trendline'),

            html.Div([
                html.Label("marginal_x (X轴边际图)", className="form-label"),
                dcc.Dropdown(
                    id='param-marginal-x',
                    options=[
                        {'label': '直方图', 'value': 'histogram'},
                        {'label': '箱线图', 'value': 'box'},
                        {'label': '小提琴图', 'value': 'violin'},
                    ],
                    value=defaults.get('marginal_x'),
                    placeholder='选择X轴边际图（可选）',
                    clearable=True,
                    className='mb-2'
                ),
            ], id='wrapper-param-marginal-x'),

            html.Div([
                html.Label("marginal_y (Y轴边际图)", className="form-label"),
                dcc.Dropdown(
                    id='param-marginal-y',
                    options=[
                        {'label': '直方图', 'value': 'histogram'},
                        {'label': '箱线图', 'value': 'box'},
                        {'label': '小提琴图', 'value': 'violin'},
                    ],
                    value=defaults.get('marginal_y'),
                    placeholder='选择Y轴边际图（可选）',
                    clearable=True,
                    className='mb-2'
                ),
            ], id='wrapper-param-marginal-y'),

        ], id='advanced-params-collapse', is_open=any(defaults.get(key) for key in (
            'hover_data', 'facet_row', 'facet_col', 'animation_frame', 'trendline', 'marginal_x', 'marginal_y'
        ))),

        # ── 隐藏占位符：generate_chart 回调 Input 需要这些 ID 存在 ──
        html.Div([
            dcc.Dropdown(id='param-palette', value=defaults.get('palette')),
            dcc.Dropdown(id='param-style', value=defaults.get('style')),
        ], style={'display': 'none'}),

        # 图表样式
        _create_style_panel(defaults),

    ], className='params-panel')



def create_seaborn_params_panel(df: pd.DataFrame, defaults: dict | None = None) -> html.Div:
    """创建 Seaborn 参数配置面板"""
    defaults = defaults or {}
    columns = get_labeled_options(df)

    return html.Div([
        html.H6("Seaborn 参数", className="mb-3"),

        html.Div([
            html.Label("x (X轴)", className="form-label"),
            dcc.Dropdown(
                id='param-x',
                options=columns,
                value=defaults.get('x'),
                placeholder='选择X轴字段',
                className='mb-2'
            ),
        ]),

        html.Div([
            html.Label("y (Y轴)", className="form-label"),
            dcc.Dropdown(
                id='param-y',
                options=columns,
                value=defaults.get('y'),
                placeholder='选择Y轴字段',
                className='mb-2'
            ),
            dbc.Checkbox(
                id='param-secondary-y-check',
                label='启用辅助 Y 轴 (双Y坐标轴)',
                value=bool(defaults.get('secondary_y')),
                className='mb-1 mt-2',
                style={'fontSize': '12px', 'color': 'var(--text-muted)'}
            ),
            html.Div(id='wrap-secondary-y-col', style={'display': 'none'}, children=[
                dcc.Dropdown(
                    id='param-secondary-y-col',
                    options=columns,
                    value=defaults.get('secondary_y'),
                    placeholder='选择额外的数值字段...',
                    className='mb-2',
                    clearable=True
                )
            ])
        ]),

        html.Div([
            html.Label("hue (颜色分组)", className="form-label"),
            dcc.Dropdown(
                id='param-color',  # 统一为 param-color，与 Plotly 面板及 generate_chart 回调 Input 保持一致
                options=columns,
                value=defaults.get('color') or defaults.get('hue'),
                placeholder='选择颜色字段（可选）',
                clearable=True,
                className='mb-2'
            ),
        ]),

        html.Div([
            html.Label("size (大小)", className="form-label"),
            dcc.Dropdown(
                id='param-size',
                options=columns,
                value=defaults.get('size'),
                placeholder='选择大小字段（可选）',
                clearable=True,
                className='mb-2'
            ),
        ]),

        html.Div([
            html.Label("style (样式)", className="form-label"),
            dcc.Dropdown(
                id='param-style',
                options=columns,
                value=defaults.get('style'),
                placeholder='选择样式字段（可选）',
                clearable=True,
                className='mb-2'
            ),
        ]),

        html.Hr(),

        html.Div([
            html.Label("palette (调色板)", className="form-label"),
            dcc.Dropdown(
                id='param-palette',
                options=[
                    {'label': 'deep', 'value': 'deep'},
                    {'label': 'muted', 'value': 'muted'},
                    {'label': 'pastel', 'value': 'pastel'},
                    {'label': 'bright', 'value': 'bright'},
                    {'label': 'dark', 'value': 'dark'},
                    {'label': 'colorblind', 'value': 'colorblind'},
                    {'label': 'viridis', 'value': 'viridis'},
                    {'label': 'plasma', 'value': 'plasma'},
                ],
                value=defaults.get('palette', 'deep'),
                clearable=False,
                className='mb-2'
            ),
        ]),

        # ── 隐藏占位符：generate_chart 回调 Input 需要这些 ID 存在 ──
        # 当切换到 Seaborn 模式时，Plotly 专用的参数组件不存在，
        # 但 Dash 回调机制要求所有 Input 组件必须在 DOM 中，
        # 否则回调会静默失败。以下隐藏 Dropdown 确保 ID 可达。
        html.Div([
            dcc.Dropdown(id='param-z', value=defaults.get('z')),
            dcc.Dropdown(id='param-text', value=defaults.get('text')),
            dcc.Dropdown(id='param-hover-data', value=defaults.get('hover_data')),
            dcc.Dropdown(id='param-facet-row', value=defaults.get('facet_row')),
            dcc.Dropdown(id='param-facet-col', value=defaults.get('facet_col')),
            dcc.Dropdown(id='param-animation-frame', value=defaults.get('animation_frame')),
            dcc.Dropdown(id='param-trendline', value=defaults.get('trendline')),
            dcc.Dropdown(id='param-marginal-x', value=defaults.get('marginal_x')),
            dcc.Dropdown(id='param-marginal-y', value=defaults.get('marginal_y')),
        ], style={'display': 'none'}),

        # 图表样式
        _create_style_panel(defaults),

    ], className='params-panel')

@callback(
    Output('wrap-secondary-y-col', 'style'),
    Input('param-secondary-y-check', 'value'),
    prevent_initial_call=True
)
def toggle_secondary_y(is_checked):
    if is_checked:
        return {'display': 'block', 'animation': 'fadeIn 0.3s ease-in-out'}
    return {'display': 'none'}

# ============================================================================
# 回调函数
# ============================================================================

@callback(
    [Output('chart-type-selector', 'options'),
     Output('params-panel-container', 'children'),
     Output('library-info', 'children')],
    Input('chart-library-selector', 'value'),
    Input('chart-editor-prefill-store', 'data'),
)
def switch_library(library, editor_prefill):
    """切换图表库时更新参数面板"""
    if ctx.triggered_id == 'chart-editor-prefill-store' and (not isinstance(editor_prefill, dict) or not editor_prefill.get('pending')):
        return no_update, no_update, no_update

    dm = DataManager()
    df = dm.active_df

    if df is None or df.empty:
        return [], html.Div("请先加载数据"), ""

    defaults = {}
    if isinstance(editor_prefill, dict) and editor_prefill.get('pending') and editor_prefill.get('library') == library:
        defaults = editor_prefill.get('params') or {}

    if library == 'plotly':
        options = []
        categories = {}
        for chart_type, info in PLOTLY_CHART_TYPES.items():
            category = info['category']
            if category not in categories:
                categories[category] = []
            categories[category].append({'label': f"{info['name']} [{category}]", 'value': chart_type.value if hasattr(chart_type, 'value') else chart_type})

        for category, items in categories.items():
            options.extend(items)

        params_panel = create_plotly_params_panel(df, defaults)
        info = "Plotly：交互式图表，支持缩放、悬停、动画等功能"
    else:
        options = []
        for chart_type, info_item in SEABORN_CHART_TYPES.items():
            options.append({'label': f"{info_item['name']} [{info_item['category']}]", 'value': chart_type.value if hasattr(chart_type, 'value') else chart_type})

        params_panel = create_seaborn_params_panel(df, defaults)
        info = "Seaborn：静态图表，更美观的默认样式，适合出版和报告"

    return options, params_panel, info


@callback(
    Output('advanced-params-collapse', 'is_open'),
    Input('toggle-advanced-params', 'n_clicks'),
    State('advanced-params-collapse', 'is_open'),
    prevent_initial_call=True
)
def toggle_advanced_params(n_clicks, is_open):
    """切换高级参数面板"""
    return not is_open


@callback(
    [Output('param-y', 'options'),
     Output('param-color', 'options'),
     Output('param-size', 'options'),
     Output('chart-recommendations', 'children')],
    [Input('param-x', 'value'),
     Input('param-y', 'value'),
     Input('param-color', 'value')],
    prevent_initial_call=False
)
def validate_params(x_val, y_val, color_val):
    """校验参数，避免重复选择 + 更新图表推荐"""
    dm = DataManager()
    df = dm.active_df

    if df is None or df.empty:
        return [], [], [], "请先加载数据"

    all_columns = get_labeled_options(df)

    y_options = [opt for opt in all_columns if opt['value'] != x_val]
    color_options = [opt for opt in all_columns if opt['value'] not in [x_val, y_val]]
    size_options = [opt for opt in all_columns if opt['value'] not in [x_val, y_val, color_val]]

    # 智能图表推荐
    if x_val or y_val:
        recs = ChartRecommender.recommend(df, x=x_val, y=y_val, color=color_val)
        if recs:
            rec_cards = []
            for rec in recs:
                rec_cards.append(
                    html.Div([
                        html.Div([
                            html.I(className=f"{rec.icon} me-2", style={"fontSize": "1.2rem", "color": "var(--text-muted)", "marginBottom": "2px"}),
                            html.Span(rec.name, className="ms-1",
                                      style={"fontWeight": "600", "fontSize": "0.85rem", "pointerEvents": "none"}),
                            html.Span(f" {rec.score}分",
                                      style={"fontSize": "0.7rem", "color": "var(--success)",
                                             "marginLeft": "auto", "pointerEvents": "none"}),
                        ], className="d-flex align-items-center", style={"pointerEvents": "none"}),
                    ],
                        className='p-2 mb-1 filter-condition-card filter-group-card',
                        id={'type': 'rec-card', 'index': rec.chart_type},
                        n_clicks=0,
                        style={"cursor": "pointer"}
                    )
                )
            recommend_content = html.Div(rec_cards)
        else:
            recommend_content = "暂无推荐，请尝试选择不同的字段"
    else:
        recommend_content = "选择 X/Y 轴后将显示推荐图表"

    return y_options, color_options, size_options, recommend_content


def _parse_chart_error(e: Exception, library: str, chart_type: str) -> tuple[str, str, str]:
    """解析图表生成错误并返回友好的提示信息。返回 (错误类型, 错误详情, 解决建议)"""
    err_str = str(e).lower()
    
    # 针对各图表类型的参数要求说明
    chart_reqs = {
        "scatter": "散点图：X 和 Y 建议为数值型或时间型，【点大小 (Size) 必须是纯数值型】，【颜色 (Color)】可以是数值或分类。",
        "line": "折线图：X 轴通常为时间或连续序列，Y 轴【必须是数值型】。",
        "bar": "柱状图：X 轴(或Y轴)为分类标签，另一轴【必须是数值型】统计算法。",
        "pie": "饼图：【数值 (Values/Hover)】必须是纯数值型，名称/颜色建议为分类文本。",
        "sunburst": "旭日图：路径(层级)为分类文本，数值(Size/Values)【必须是纯数值型】。",
        "treemap": "树状图：同旭日图，层级结构要求分类，【数值块大小必须是数值】。",
        "heatmap": "热力图：X 和 Y 通常为分类标签构成网格，【Z 轴或计算值 (Values) 必须是纯数值型】。",
        "box": "箱线图：通常分配一个分类轴和一个【数值轴】用来计算分位数。",
        "violin": "小提琴图：【必须包含至少一个数值轴】用来计算核密度分布。",
        "histogram": "直方图：X 或 Y 轴【必须是连续的数值型】，用于分箱统计频率。"
    }
    
    req_hint = chart_reqs.get(chart_type, f"当前图表 ({chart_type}) 要求明确的维度和度量区分，通常颜色/大小/Z轴严格需要数值。")

    # Plotly 常见错误
    if library == 'plotly':
        if "string column" in err_str and "size" in err_str:
            return "参数类型冲突 (Size)", str(e), f"❌ 错误定位：您把包含文字（字符串）的列放在了【点大小 Size】中。\n📊 逻辑规范：{req_hint}"
        if "string column" in err_str and "y" in err_str:
             return "参数类型冲突 (Y轴)", str(e), f"❌ 错误定位：当前图表的 Y 轴不允许传入分类(文本)列，需要连续的数值。\n📊 逻辑规范：{req_hint}"
        if "not numeric" in err_str:
            return "需要数值型数据 (Numeric Required)", str(e), f"❌ 错误定位：向要求算术计算的字段传了非数值列（通常发生在大小、Z轴或数值指标上）。\n📊 逻辑规范：{req_hint}"
        if "all arguments should have the same length" in err_str:
             return "数组长度不匹配", str(e), "❌ 错误定位：输入特征之间存在空缺对不齐，请尝试在数据工坊先\"删除包含缺失值的行\"。"
        
    # Seaborn 常见错误
    if library == 'seaborn':
        if "could not convert string to float" in err_str:
            return "强制类型转换失败 (String->Float)", "有不可转为数字的文本参与了绘图", f"❌ 错误定位：你可能把分类/文字列强行塞进了只接受连续数值的参数槽（比如热力图的运算区）。\n📊 逻辑规范：{req_hint}"
        if "categorical" in err_str and "size" in err_str:
            return "参数映射异常 (Size)", str(e), f"❌ 错误定位：Seaborn 不支持用非数值分类的文本来决定点的大小。\n📊 逻辑规范：{req_hint}"
        if "no numeric data to plot" in err_str:
            return "找不到有效的数值参与制图", str(e), f"❌ 错误定位：没有捕捉到可以用作计算边界或热力的数字序列。你可能只选中了文本列。\n📊 逻辑规范：{req_hint}"
        if "cannot use `hue` without `x` and `y`" in err_str:
            return "缺少基础坐标轴", str(e), "❌ 错误定位：你分配了颜色分类 (Hue)，但丢失了基本的 X 或 Y 映射。"
        
    # 通用错误
    if "keyerror" in err_str or "not in index" in err_str:
        return "所选字段已丢失或不存在", str(e), "❌ 错误定位：该列在原始数据中找不到。可能在预处理阶段被重命名或删除了，建议刷新字段下拉框重新选择。"
        
    # 默认回退
    return "组合图表所需参数不符合引擎限制", str(e), f"❌ 错误定位：未命中已知规则，推测为核心数值/分类参数被错位放置。\n📊 图表规范参考：{req_hint}\n👉 请重新核实 X、Y、Color、Size 各坑位的选中状态。"


@callback(
    [Output('chart-container', 'children'),
     Output('generated-code-display', 'value'),
     Output('chart-figure-store', 'data'),
     Output('chart-data-store', 'data')],
    [Input('chart-type-selector', 'value'),
     Input('param-x', 'value'),
     Input('param-y', 'value'),
     Input('param-z', 'value'),
     Input('param-color', 'value'),
     Input('param-size', 'value'),
     Input('param-text', 'value'),
     Input('param-hover-data', 'value'),
     Input('param-facet-row', 'value'),
     Input('param-facet-col', 'value'),
     Input('param-animation-frame', 'value'),
     Input('param-trendline', 'value'),
     Input('param-marginal-x', 'value'),
     Input('param-marginal-y', 'value'),
     Input('param-palette', 'value'),
     Input('param-style', 'value'),
     Input('style-title', 'value'),
     Input('style-template', 'value'),
     Input('style-color-scale', 'value'),
     Input('style-show-legend', 'value'),
     Input('style-show-grid', 'value'),
     Input('param-secondary-y-check', 'value'),
     Input('param-secondary-y-col', 'value'),
     Input('style-opacity', 'value'),
     Input('style-width', 'value'),
     Input('style-height', 'value')],
    [State('chart-library-selector', 'value')],
    prevent_initial_call=True
)
def generate_chart(
    chart_type, x, y, z, color, size, text, hover_data,
    facet_row, facet_col, animation_frame,
    trendline, marginal_x, marginal_y,
    param_palette, param_style,
    style_title, style_template, style_color_scale,
    style_show_legend, style_show_grid,
    param_secondary_y_check, param_secondary_y_col, style_opacity,
    style_width, style_height,
    library
):
    """???????"""
    dm = DataManager()
    df = dm.active_df

    if df is None or df.empty:
        return html.Div("??????"), "# ??????", None, None

    if not x and not y:
        return html.Div("?????X??Y?"), "# ?????", None, None

    if library == 'plotly':
        params = {
            'x': x,
            'y': y,
            'z': z,
            'color': color,
            'size': size,
            'text': text,
            'hover_data': hover_data,
            'facet_row': facet_row,
            'facet_col': facet_col,
            'animation_frame': animation_frame,
            'trendline': trendline,
            'marginal_x': marginal_x,
            'marginal_y': marginal_y,
            'title': style_title,
            'template': style_template or 'plotly_white',
            'color_scale': style_color_scale if style_color_scale else None,
            'show_legend': style_show_legend if style_show_legend is not None else True,
            'show_grid': style_show_grid if style_show_grid is not None else True,
            'secondary_y': param_secondary_y_col if param_secondary_y_check else None,
            'opacity': style_opacity,
            'width': style_width,
            'height': style_height,
        }
    else:
        params = {
            'x': x,
            'y': y,
            'hue': color,
            'size': size,
            'style': param_style,
            'palette': param_palette or 'deep',
            'title': style_title,
            'show_grid': style_show_grid if style_show_grid is not None else True,
            'show_legend': style_show_legend if style_show_legend is not None else True,
            'secondary_y': param_secondary_y_col if param_secondary_y_check else None,
            'width': style_width or 800,
            'height': style_height or 480,
            'template': style_template,
            'color_scale': style_color_scale,
        }

    params = {k: v for k, v in params.items() if v is not None}
    chart_config = _build_chart_config(library, chart_type, params, style_title)

    try:
        chart_service = ChartService()
        chart_service.set_library(ChartLibrary(library))

        if not chart_type:
            return html.Div("????????"), "# ????????", None, None

        result = chart_service.create_chart(
            df=df,
            chart_type=ChartType(chart_type),
            params=params
        )

        code = CodeGenerator.generate_code(
            library=library,
            chart_type=chart_type,
            params=params
        )

        if library == 'plotly':
            fig_json = result['chart']
            chart_component = dcc.Graph(
                figure=json.loads(fig_json),
                config={'displayModeBar': True, 'displaylogo': False},
                style={'height': '100%'}
            )
            return chart_component, code, fig_json, chart_config

        chart_component = html.Img(
            src=result['chart'],
            style={'width': '100%', 'maxHeight': '500px', 'objectFit': 'contain'}
        )
        return chart_component, code, result['chart'], chart_config

    except Exception as e:
        err_title, err_detail, err_suggestion = _parse_chart_error(e, library, chart_type)
        error_ui = dbc.Alert(
            [
                html.H6([html.I(className="bi bi-exclamation-triangle-fill me-2"), err_title], className="alert-heading text-danger"),
                html.P(err_detail, className="mb-2 text-muted", style={"fontSize": "0.85rem", "wordBreak": "break-all"}),
                html.Hr(className="my-2"),
                html.P([html.B("?? ?????", className="text-secondary"), err_suggestion], className="mb-0")
            ],
            color="light",
            className="shadow-sm border-start border-danger border-4",
            style={"maxWidth": "80%", "margin": "0 auto", "marginTop": "10%"}
        )
        return error_ui, f"# {err_title}: {err_detail}\n# ????: {err_suggestion}", None, None

@callback(
    Output('download-chart-file', 'data'),
    Input('export-png-btn', 'n_clicks'),
    Input('export-svg-btn', 'n_clicks'),
    Input('export-html-btn', 'n_clicks'),
    State('chart-figure-store', 'data'),
    State('chart-library-selector', 'value'),
    prevent_initial_call=True
)
def export_chart(png_clicks, svg_clicks, html_clicks, fig_json, library):
    """导出图表为 PNG/SVG/HTML"""
    from dash import ctx
    if not fig_json or library != 'plotly':
        return no_update

    triggered = ctx.triggered_id

    try:
        import plotly.io as pio
        fig = go.Figure(json.loads(fig_json))

        if triggered == 'export-png-btn':
            img_bytes = pio.to_image(fig, format='png', width=1200, height=700, scale=2)
            import base64
            b64 = base64.b64encode(img_bytes).decode()
            return dict(
                content=b64,
                filename='chart.png',
                base64=True
            )
        elif triggered == 'export-svg-btn':
            img_bytes = pio.to_image(fig, format='svg', width=1200, height=700)
            return dict(
                content=img_bytes.decode('utf-8'),
                filename='chart.svg'
            )
        elif triggered == 'export-html-btn':
            html_str = pio.to_html(fig, full_html=True, include_plotlyjs='cdn')
            return dict(
                content=html_str,
                filename='chart.html'
            )
    except ImportError:
        # kaleido not installed for image export
        return no_update
    except Exception:
        return no_update

    return no_update


@callback(
    Output('download-code-file', 'data'),
    Input('download-py-btn', 'n_clicks'),
    State('generated-code-display', 'value'),
    prevent_initial_call=True
)
def download_code(n_clicks, code):
    """?? Python ??"""
    if not code or code.startswith('#'):
        return None

    return dict(
        content=code,
        filename='chart_code.py'
    )


@callback(
    Output('download-jupyter-file', 'data'),
    Input('export-jupyter-btn', 'n_clicks'),
    State('generated-code-display', 'value'),
    State('chart-data-store', 'data'),
    prevent_initial_call=True
)
def download_jupyter_notebook(n_clicks, code, chart_config):
    if not n_clicks or not code or code.startswith('#'):
        return no_update

    return dict(
        content=_build_notebook_content(code, chart_config),
        filename='chart_code.ipynb'
    )

@callback(
    Output('copy-success-toast', 'is_open'),
    Input('copy-code-btn', 'n_clicks'),
    State('generated-code-display', 'value'),
    prevent_initial_call=True
)
def copy_code(n_clicks, code):
    """复制代码到剪贴板（显示提示）"""
    if not code or code.startswith('#'):
        return False
    return True


# Clientside callback for actual clipboard copy
from dash import clientside_callback, ClientsideFunction

clientside_callback(
    ClientsideFunction(
        namespace='clientside',
        function_name='copyToClipboard'
    ),
    Output('copy-code-btn', 'n_clicks'),
    Input('copy-code-btn', 'n_clicks'),
    State('generated-code-display', 'value'),
    prevent_initial_call=True
)

@callback(
    [Output('wrapper-param-z', 'style'),
     Output('wrapper-param-size', 'style'),
     Output('wrapper-param-text', 'style')],
    Input('chart-type-selector', 'value'),
    prevent_initial_call=False
)
def toggle_param_visibility_plotly(chart_type):
    """根据图表类别隐藏不用填写的字段，让UI变得整洁清爽"""
    show = {'display': 'block'}
    hide = {'display': 'none'}
    
    # 比如仅3D散点和曲面能用 Z 轴
    z_style = show if chart_type in ('scatter_3d', 'surface_3d') else hide
    
    # 折线、直方图、瀑布等无 Size 需要
    size_style = hide if chart_type in ('bar', 'hbar', 'histogram', 'box', 'violin', 'area', 'waterfall', 'pie', 'sunburst', 'treemap', 'funnel', 'contour', 'surface_3d') else show
    
    # 文本支持情况
    text_style = hide if chart_type in ('histogram', 'box', 'violin', 'density_heatmap', 'contour', 'surface_3d', 'sunburst', 'treemap', 'parallel', 'parallel_cat', 'splom') else show
    
    return z_style, size_style, text_style

@callback(
    Output('chart-type-selector', 'value'),
    Input({'type': 'rec-card', 'index': ALL}, 'n_clicks'),
    prevent_initial_call=True
)
def handle_recommendation_click(n_clicks_list):
    """支持点击图表推荐小卡片后快速切换主图型"""
    if not ctx.triggered:
        return no_update
    
    trigger_prop = ctx.triggered[0]['prop_id'].split('.')[0]
    
    try:
        trigger_dict = json.loads(trigger_prop)
        t_type = trigger_dict.get('type')
        chart_selected = trigger_dict.get('index')
        
        if t_type == 'rec-card' and chart_selected:
            # 如果对应的卡片 n_clicks > 0 才切换
            triggered_value = ctx.triggered[0]['value']
            if triggered_value and triggered_value > 0:
                return chart_selected
    except Exception:
        pass
        
    return no_update


# ============================================================================
# 画廊保存与渲染回调
# ============================================================================

@callback(
    Output('saved-charts-store', 'data'),
    Output('save-success-toast', 'is_open'),
    Input('btn-save-chart', 'n_clicks'),
    Input('btn-clear-gallery', 'n_clicks'),
    State('chart-figure-store', 'data'),
    State('chart-data-store', 'data'),
    State('chart-library-selector', 'value'),
    State('chart-type-selector', 'value'),
    State('saved-charts-store', 'data'),
    prevent_initial_call=True
)
def handle_gallery_actions(save_clicks, clear_clicks, fig_data, chart_data, library, chart_type, saved_data):
    """?????????????"""
    ctx_id = ctx.triggered_id
    normalized_saved = []
    if isinstance(saved_data, list):
        normalized_saved = [item for item in (_normalize_saved_chart(entry) for entry in saved_data) if item]

    if ctx_id == 'btn-clear-gallery':
        return [], False

    if ctx_id == 'btn-save-chart':
        if not fig_data:
            return no_update, False

        config = chart_data or _build_chart_config(library, chart_type, {}, None)
        new_item = {
            'id': f"chart_{uuid.uuid4().hex}",
            'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            'library': config.get('library', library),
            'chart_type': config.get('chart_type', chart_type),
            'figure': fig_data,
            'config': config,
        }
        normalized_saved.insert(0, new_item)
        return normalized_saved, True

    return no_update, no_update


@callback(
    Output('chart-gallery-grid', 'children'),
    Input('saved-charts-store', 'data')
)
def update_gallery(saved_data):
    """?????????? Tab ???????"""
    normalized_saved = []
    if isinstance(saved_data, list):
        normalized_saved = [item for item in (_normalize_saved_chart(entry) for entry in saved_data) if item]

    if not normalized_saved:
        return html.Div([
            html.I(className="bi bi-images", style={"fontSize": "4rem", "color": "var(--text-muted)"}),
            html.P("?????", className="text-muted mt-3", style={"fontSize": "1.1rem"}),
            html.P("??????????????????????", className="text-muted", style={"fontSize": "0.875rem"}),
        ], className="text-center", style={"paddingTop": "15vh"})

    cards = []
    for item in normalized_saved:
        library = item.get('library', 'unknown')
        fig_data = item.get('figure')
        chart_type = item.get('chart_type', 'Chart')
        chart_title = item.get('config', {}).get('title') or f"{str(chart_type).capitalize()} ??"

        try:
            if library == 'plotly' and isinstance(fig_data, str):
                chart_content = dcc.Graph(
                    figure=json.loads(fig_data),
                    config={'displayModeBar': False},
                    style={"height": "220px", "width": "100%"}
                )
            elif library == 'seaborn' and isinstance(fig_data, str):
                chart_content = html.Img(
                    src=fig_data,
                    style={"maxWidth": "100%", "maxHeight": "220px", "objectFit": "contain"}
                )
            else:
                chart_content = html.Div("????", className="text-muted")
        except Exception:
            chart_content = html.Div("????", className="text-muted")

        card = dbc.Card([
            dbc.CardBody([
                html.Div(chart_content, className="d-flex justify-content-center align-items-center mb-3", style={"height": "220px", "backgroundColor": "white", "borderRadius": "4px", "overflow": "hidden", "padding": "4px"}),
                html.H6(f"{chart_title}", className="card-title text-truncate", style={"fontSize": "0.95rem", "fontWeight": "bold"}),
                html.Div([
                    dbc.Badge(library.capitalize(), color="primary" if library == "plotly" else "info", className="me-2"),
                    html.Small(item.get('timestamp', ''), className="text-muted")
                ], className="d-flex justify-content-between align-items-center mt-2"),
                dbc.Button(
                    [html.I(className="bi bi-pencil-square me-2"), "继续编辑"],
                    id={"type": "gallery-edit-chart", "index": item["id"]},
                    color="primary",
                    outline=True,
                    size="sm",
                    className="mt-3 w-100 btn-hover",
                ),
            ], className="p-3")
        ], className="h-100 shadow-sm", style={"border": "1px solid var(--border)", "backgroundColor": "var(--bg-secondary)"})

        cards.append(dbc.Col(card, xs=12, sm=6, md=6, lg=4, xl=3, className="mb-4"))

    return dbc.Row(cards)


@callback(
    Output("chart-studio-tabs", "active_tab", allow_duplicate=True),
    Output("chart-library-selector", "value", allow_duplicate=True),
    Output("chart-type-selector", "value", allow_duplicate=True),
    Output("chart-editor-prefill-store", "data", allow_duplicate=True),
    Output("chart-figure-store", "data", allow_duplicate=True),
    Output("chart-data-store", "data", allow_duplicate=True),
    Output("chart-container", "children", allow_duplicate=True),
    Input({"type": "gallery-edit-chart", "index": ALL}, "n_clicks"),
    State("saved-charts-store", "data"),
    prevent_initial_call=True,
)
def load_chart_from_gallery(_, saved_data):
    if not ctx.triggered_id:
        return (no_update,) * 7

    chart_id = ctx.triggered_id.get("index")
    normalized_saved = []
    if isinstance(saved_data, list):
        normalized_saved = [item for item in (_normalize_saved_chart(entry) for entry in saved_data) if item]

    selected = next((item for item in normalized_saved if item.get("id") == chart_id), None)
    if not selected:
        return (no_update,) * 7

    prefill = _build_editor_prefill(selected)
    if not prefill:
        return (no_update,) * 7

    return (
        "tab-explore",
        prefill.get("library"),
        prefill.get("chart_type"),
        prefill,
        prefill.get("figure"),
        prefill.get("config"),
        _render_chart_from_state(prefill.get("figure"), prefill.get("config")),
    )


@callback(
    Output("chart-editor-prefill-store", "data", allow_duplicate=True),
    Input("params-panel-container", "children"),
    State("chart-editor-prefill-store", "data"),
    prevent_initial_call=True,
)
def clear_gallery_prefill(_, prefill):
    if not isinstance(prefill, dict) or not prefill.get("pending"):
        return no_update

    cleared = dict(prefill)
    cleared["pending"] = False
    return cleared


@callback(
    Output("ai-chart-display", "children"),
    Input("chart-figure-store", "data"),
    Input("chart-data-store", "data"),
)
def update_ai_chart_snapshot(fig_data, config_data):
    if not fig_data or not config_data:
        return html.Div("?????????????", className="text-muted")

    lib = config_data.get('library')
    if lib == 'plotly':
        try:
            figure = json.loads(fig_data) if isinstance(fig_data, str) else fig_data
        except Exception:
            return html.Div("????????", className="text-danger")
        return dcc.Graph(figure=figure, config={'displayModeBar': False}, style={"width": "100%", "height": "100%"})
    if lib == 'seaborn':
        return html.Img(src=fig_data, style={'maxWidth': '100%', 'maxHeight': '100%', 'objectFit': 'contain'})

    return html.Div("????????", className="text-danger")


@callback(
    Output("ai-analysis-output", "children"),
    Input("btn-generate-ai", "n_clicks"),
    State("ai-api-base", "value"),
    State("ai-api-key", "value"),
    State("ai-api-model", "value"),
    State("chart-data-store", "data"),
    prevent_initial_call=True
)
def generate_ai_analysis(n_clicks, api_base, api_key, model, chart_data):
    if not n_clicks:
        return no_update
    if not api_key:
        return "⚠️ 请先在配置中填入 API Key。"
    if not chart_data:
        return "⚠️ 当前没有生成图表，请先在「图表探索」中生成一张图表。"

    try:
        dm = DataManager()
        df = dm.active_df
        if df is None:
            return "⚠️ 数据未加载。"
            
        summary = {
            "Rows": len(df),
            "Columns": len(df.columns),
            "Missing_Values": df.isnull().sum().to_dict(),
        }
        
        # 提取图表配置
        chart_type = chart_data.get("chart_type", "未知")
        params = chart_data.get("params", {})
        
        prompt = f"""
你是一位资深的数据分析专家和商业顾问。请基于以下数据集的概况信息和刚刚生成的图表配置，给出专业且有深度的业务洞察。

数据集概况：
{json.dumps(summary, ensure_ascii=False, indent=2)}

当前绘制的图表要素：
- 图表类型：{chart_type}
- 参数配置：{json.dumps(params, ensure_ascii=False, indent=2)}

请按照以下结构输出你的分析结论：
1. 【图表结构说明】：概括图表配置展现出的主要维度和可能呈现的规律。
2. 【异常发现在哪】：推测在此类特征组合下，可能存在的极值、离群点现象，并指导我如何从图中鉴别。
3. 【潜在业务洞察】：结合一般商业逻辑思维，解释该特征组合背后的潜在因果或关联。
4. 【后续行动建议】：给出 1-2 条落地的后续数据分析探索方向。

注意：使用严谨的 Markdown 格式，不要输出任何对话客套话，直接给出专业分析。
"""
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": "You are a helpful and professional data analyzer."},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.7
        }
        
        url = f"{api_base.rstrip('/')}/chat/completions"
        resp = requests.post(url, headers=headers, json=payload, timeout=40)
        
        if resp.status_code == 200:
            data = resp.json()
            return data["choices"][0]["message"]["content"]
        else:
            return f"❌ API 请求失败 (状态码 {resp.status_code}): \n```json\n{resp.text}\n```"
            
    except Exception as e:
        return f"❌ 请求或解析过程中发生异常：\n```\n{str(e)}\n```"

# ── AI 分析保存报告 ─────────────────────────────────────
@callback(
    Output("download-chart-file", "data", allow_duplicate=True),
    Input("btn-save-ai", "n_clicks"),
    State("ai-analysis-output", "children"),
    prevent_initial_call=True
)
def download_ai_report(n_clicks, ai_content):
    if not n_clicks or not ai_content:
        return no_update
    return dcc.send_string(ai_content, "图表智能分析报告.md")


@callback(
    Output("project-page-store", "data", allow_duplicate=True),
    Input("chart-studio-tabs", "active_tab"),
    Input("chart-library-selector", "value"),
    Input("chart-type-selector", "value"),
    Input("style-title", "value"),
    Input("chart-figure-store", "data"),
    Input("chart-data-store", "data"),
    Input("saved-charts-store", "data"),
    State("project-page-store", "data"),
    prevent_initial_call=True,
)
def sync_chart_project_state(active_tab, library, chart_type, title, figure_data, chart_data, saved_charts, project_state):
    state = dict(project_state or {})
    state["chart_studio"] = {
        "active_tab": active_tab or "tab-explore",
        "library": library or "plotly",
        "chart_type": chart_type,
        "title": title,
        "figure_data": figure_data,
        "chart_data": chart_data,
        "saved_charts": saved_charts or [],
    }
    return state


@callback(
    Output("chart-studio-tabs", "active_tab", allow_duplicate=True),
    Output("chart-library-selector", "value", allow_duplicate=True),
    Output("chart-type-selector", "value", allow_duplicate=True),
    Output("style-title", "value", allow_duplicate=True),
    Output("chart-figure-store", "data", allow_duplicate=True),
    Output("chart-data-store", "data", allow_duplicate=True),
    Output("saved-charts-store", "data", allow_duplicate=True),
    Output("chart-container", "children", allow_duplicate=True),
    Input("project-restore-store", "data"),
    Input("url", "pathname"),
    prevent_initial_call=True,
)
def restore_chart_project_state(project_restore, pathname):
    if pathname != "/charts" or not project_restore:
        return (no_update,) * 8

    page_state = (project_restore.get("page_state") or {}).get("chart_studio")
    if not page_state:
        return (no_update,) * 8

    active_tab = page_state.get("active_tab", "tab-explore")
    library = page_state.get("library", "plotly")
    chart_type = page_state.get("chart_type")
    title = page_state.get("title")
    figure_data = page_state.get("figure_data")
    chart_data = page_state.get("chart_data")
    saved_charts = page_state.get("saved_charts", [])
    chart_component = _render_chart_from_state(figure_data, chart_data)
    return active_tab, library, chart_type, title, figure_data, chart_data, saved_charts, chart_component
