# -*- coding: utf-8 -*-
"""
Phase 3 手动测试检查清单
运行应用后，按照此清单逐项测试
"""
import sys
import io

# 设置输出编码为 UTF-8
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

print("=" * 70)
print("DataViz Studio - Phase 3 功能测试清单")
print("=" * 70)

print("\nPhase 3 要求（来自 design_prompts_standalone.md）：")
print("  [OK] 数据清洗面板 + 操作流水线")
print("  [OK] 描述性统计 + 相关性分析")
print("  [OK] 筛选构建器")
print("  [OK] 代码生成功能")

print("\n" + "=" * 70)
print("测试步骤")
print("=" * 70)

print("\n[1] 启动应用")
print("   命令: python app.py")
print("   访问: http://127.0.0.1:8050")

print("\n[2] 加载测试数据")
print("   - 进入欢迎页")
print("   - 点击「使用示例数据」或上传 CSV 文件")
print("   - 确认数据加载成功")

print("\n[3] 测试数据工坊 (Data Workshop)")
print("   URL: http://127.0.0.1:8050/data-workshop")
print()
print("   3.1 列操作")
print("       [ ] 删除列 - 选择列并删除")
print("       [ ] 重命名列 - 修改列名")
print("       [ ] 拆分列 - 按分隔符拆分")
print("       [ ] 合并列 - 合并多列")
print()
print("   3.2 缺失值处理")
print("       [ ] 查看缺失值 - 显示缺失值统计")
print("       [ ] 填充缺失值 - 用均值/中位数/众数填充")
print("       [ ] 删除缺失行 - 删除包含缺失值的行")
print()
print("   3.3 数据类型转换")
print("       [ ] 转换类型 - 转换列的数据类型")
print("       [ ] 智能检测 - 自动检测并转换类型")
print()
print("   3.4 筛选与排序")
print("       [ ] 添加筛选条件 - 创建筛选规则")
print("       [ ] 排序数据 - 按列排序")
print()
print("   3.5 操作流水线")
print("       [ ] 查看操作历史 - 显示所有操作")
print("       [ ] 删除单个操作 - 点击 × 删除")
print("       [ ] 清空流水线 - 清空所有操作")
print()
print("   3.6 代码生成")
print("       [ ] 导出为 Python 脚本 - 生成可执行代码")
print("       [ ] 验证代码完整性 - 包含所有操作")

print("\n[4] 测试统计实验室 (Statistics Lab)")
print("   URL: http://127.0.0.1:8050/statistics-lab")
print()
print("   4.1 描述性统计")
print("       [ ] 选择数值列")
print("       [ ] 查看统计指标（均值、中位数、标准差等）")
print("       [ ] 查看分布图")
print()
print("   4.2 相关性分析")
print("       [ ] 选择多个数值列")
print("       [ ] 查看相关系数矩阵")
print("       [ ] 查看热力图")
print()
print("   4.3 分布分析")
print("       [ ] 选择列")
print("       [ ] 查看直方图")
print("       [ ] 查看箱线图")

print("\n[5] 测试图表工作室 (Chart Studio) - Phase 2 功能验证")
print("   URL: http://127.0.0.1:8050/chart-studio")
print()
print("   [ ] 拖拽字段到 X/Y 轴")
print("   [ ] 选择图表类型")
print("   [ ] 配置图表样式")
print("   [ ] 导出图表")

print("\n[6] 集成测试")
print("   [ ] 在数据工坊清洗数据")
print("   [ ] 在统计实验室分析数据")
print("   [ ] 在图表工作室可视化数据")
print("   [ ] 导出代码并验证可执行")

print("\n" + "=" * 70)
print("预期结果")
print("=" * 70)
print("[OK] 所有功能正常运行，无报错")
print("[OK] 操作流水线正确记录所有操作")
print("[OK] 代码生成功能生成可执行的 Python 代码")
print("[OK] 统计分析结果准确")
print("[OK] 页面切换流畅，数据状态保持")

print("\n" + "=" * 70)
print("开始测试")
print("=" * 70)
print("\n请运行: python app.py")
print("然后按照上述清单逐项测试\n")
